# Generated by Django 5.0.6 on 2024-08-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monetarycampaign',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
