# Generated by Django 5.0.6 on 2024-09-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_monetarycampaign_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monetarycampaign',
            name='end_date',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monetarycampaign',
            name='start_date',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
