# Generated by Django 5.0.6 on 2024-09-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_alter_monetarycampaign_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monetarycampaign',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monetarycampaign',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
