# Generated by Django 5.0.8 on 2024-09-05 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='name',
            new_name='institution_name',
        ),
    ]
